//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        public int IdArticulo { get; set; }
        public double StockMinArticulo { get; set; }
        public string StockMaxArticulo { get; set; }
        public string Codigo { get; set; }
        public double PrecioPromedioArticulo { get; set; }
        public decimal CantidadArticulo { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string DescripcionArticulo { get; set; }
        public string UnidadMedidaArticulo { get; set; }
        public string NombreArticulo { get; set; }
    }
}
