//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallesempleado
    {
        public int IdEmpleado { get; set; }
        public string NombreEmpleado { get; set; }
        public string CedulaEmpleado { get; set; }
        public string TelefonoOpcionalEmpleado { get; set; }
        public string DireccionEmpleado { get; set; }
        public string SexoEmpleado { get; set; }
        public byte[] FotoEmpleado { get; set; }
        public string Cargo { get; set; }
        public string IdUsers { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
