//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public int IdProveedor { get; set; }
        public string RazonSocialProveedor { get; set; }
        public string RifProveedor { get; set; }
        public int TelefonoProveedor { get; set; }
        public string DireccionProveedor { get; set; }
        public string DetallesProveedor { get; set; }
        public string NombreContactoProveedor { get; set; }
        public string SitioWebProveedor { get; set; }
    }
}
