//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
       // [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Id")]
        public int IdCliente { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Nombre")]
        public string NombreCliente { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Cedula")]
        public string CedulaCliente { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Direccion")]
        public string DireccionCliente { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha Nacimiento")]
        public System.DateTime FechaNacimientoCliente { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Telefono")]
        public string TelefonoCliente { get; set; }


        [Required(ErrorMessage = "Campo requerido")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string EmailCliente { get; set; }
    }
}
