//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacionWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class proveedor
    {
        [Display(Name = "Id")]
        public int IdProveedor { get; set; }

        [Required(ErrorMessage = "El nombre es requerido")]
        [Display(Name = "Razon Social")]
        public string RazonSocialProveedor { get; set; }

        [Required(ErrorMessage = "El RUC es requerido")]
        [Display(Name = "RUC")]
        public string RifProveedor { get; set; }

        [Required(ErrorMessage = "El Telefono es requerido")]
        [Display(Name = "Telefono Proveedor")]
        public int TelefonoProveedor { get; set; }

        [Required(ErrorMessage = "Dirección es requerido")]
        [Display(Name = "Dirección")]
        public string DireccionProveedor { get; set; }

        [Display(Name = "Detalles")]
        [Required(ErrorMessage = "Campo requerido")]
        public string DetallesProveedor { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Nombre Responsable")]
        public string NombreContactoProveedor { get; set; }

        //[DataType(DataType.Url)]
        [Required(ErrorMessage = "Url Requerida e Iniciar HTTP://")]
        [Display(Name = "Sitio Web")]
        public string SitioWebProveedor { get; set; }
    }
}
